<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>.js</string>
	</array>
	<key>name</key>
	<string>Mocha</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(describe)\("([^"]+)",\s*function\(\)\s*{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.function</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}\);</string>
			<key>name</key>
			<string>entity.section</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(it)\("([^"]+)",\s*function\((done)?\)\s*{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}\);</string>
					<key>name</key>
					<string>entity.section</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(done)\([^\)]*\)</string>
							<key>name</key>
							<string>entity.tag</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(beforeEach)\(function\((done)?\)\s*{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}\);</string>
					<key>name</key>
					<string>entity.tag</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.nodejs_mocha</string>
	<key>uuid</key>
	<string>82997f2b-0c9a-45f8-b46e-b3f3ed147fe7</string>
</dict>
</plist>
